
services:
  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  fastapi-services:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi-services
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    volumes:
      - .:/app


