
services:
  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./fastapi-services
    env_file:
      - .env
    container_name: fastapi-services
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./fastapi-services:/app

volumes:
  pgdata:
