"""Create batches table

Revision ID: 6fdc3ebd8c7c
Revises: cf60c248e157
Create Date: 2025-05-01 15:31:23.673804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdc3ebd8c7c'
down_revision: Union[str, None] = 'cf60c248e157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_foreign_key(None, 'comments', 'batches', ['batch_id'], ['id'])
    op.create_unique_constraint(None, 'likes', ['id'])
    op.create_foreign_key(None, 'posts', 'batches', ['batch_id'], ['id'])
    op.drop_index('ix_user_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
