"""Add batch_id to User

Revision ID: 8a660318e834
Revises: 6fdc3ebd8c7c
Create Date: 2025-05-01 15:42:09.269261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a660318e834'
down_revision: Union[str, None] = '6fdc3ebd8c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'batch_id')
    # ### end Alembic commands ###
