"""Add default UUID generator to likes.id

Revision ID: a8b5d403aad1
Revises: 441d3012db7a
Create Date: 2025-04-29 11:56:00.952540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b5d403aad1'
down_revision: Union[str, None] = '441d3012db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_likes_id', table_name='likes')
    op.create_unique_constraint(None, 'likes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    op.create_index('ix_likes_id', 'likes', ['id'], unique=False)
    # ### end Alembic commands ###
